language: node_js
node_js:
  - "stable"
sudo: required
before_script:
  - npm install jest
script:
  - npm test
branches:
  only:
    - master
services:
  - mongodb
env:
  - MONGODB_URI="mongodb://localhost/authentication"
notifications:
  email:
    - false
